export const products = [
  {
    href: "https://github.com/akshita270/sehatrx",
    live: "https://sehatrx.vercel.app",
    title: "SehatRx — AI-Powered Consultation to Prescription Platform",
    description:
      "A full-stack healthcare platform that listens to doctor-patient consultations, instantly transcribes them using AI, drafts structured prescriptions, and delivers them to the patient's portal the moment the doctor approves — eliminating paperwork entirely.",
    thumbnail: "🏥",
    image: "/images/projects/sehatrx.png",
    contain: true,
    color: "#0d9488",
    period: "2026",
    stack: ["React", "FastAPI", "Python", "OpenAI Whisper", "JWT", "Vercel"],
    slug: "sehatrx",
    featured: true,
    blog: "https://medium.com/@jakshita770/i-built-sehatrx-an-ai-prescription-app-for-indian-clinics-the-ai-was-the-easy-part-c097417b0d35",
    deck: "/SehatRx-Deck.pdf",
    highlights: [
      "End-to-end workflow: doctor records consultation audio → AI transcribes in real time → LLM drafts a structured prescription → doctor reviews and approves → prescription instantly appears in patient portal",
      "Role-based access for three user types: Doctor (record, review, approve), Patient (view prescriptions), and Family (view family member prescriptions)",
      "AI transcription powered by OpenAI Whisper with LLM-based prescription structuring — extracts diagnosis, medications, dosage, and instructions from free-form speech",
      "JWT-authenticated REST API backend with FastAPI; React frontend deployed on Vercel with real-time prescription delivery",
    ],
    differentiators: [
      {
        icon: "🗣️",
        title: "The doctor just talks — the paperwork writes itself.",
        body: "Instead of typing out a prescription after every patient, the doctor has a normal conversation and the app turns that into a clean, structured prescription automatically. For a doctor seeing 40+ patients a day, that's real time back.",
      },
      {
        icon: "🇮🇳",
        title: "Built for how Indian clinics actually talk.",
        body: "It listens to real consultations — Hindi, English, or the Hindi-English mix most doctors here actually speak in — and catches every word, not just the parts said in English. The prescription comes back in Hindi too, so a patient who can't read English still gets a prescription they can actually understand, even having it read aloud to them.",
      },
      {
        icon: "📱",
        title: "No more lost or illegible prescriptions.",
        body: "The moment the doctor sends it, it's instantly on the patient's portal — and a family member can be linked to see it too. No handwritten slip to lose, no blurry WhatsApp photo of a prescription nobody can read.",
      },
    ],
    engineeringNotes: [
      {
        title: "Removing claim codes without reopening the account-takeover risk",
        body: "Originally required a claim code to link a self-registered patient account to a doctor-created record, to prevent account takeover by anyone who knew a patient's email. In practice this broke onboarding for elderly patients without email, and a separate gap — no dedup check when doctors added a new patient — caused the same person to end up as two disconnected database rows, so a prescription the doctor sent was invisible from the patient's own login. Removed claim codes entirely and replaced them with phone-or-email matching plus automatic record reuse at intake, fixing the onboarding friction and the duplicate-record bug's root cause in one pass.",
      },
    ],
    caseStudy: {
      problemHeadline: "Doctors in Indian clinics spend more time on paperwork than on patients.",
      problem: "A doctor seeing 40+ patients a day handwrites prescriptions for each one — slow, error-prone, and often illegible. Patients lose slips, can't read them, or can't share them with family. No existing tool was built for how Indian clinics actually work.",
      solutionHeadline: "The doctor talks. The prescription writes itself.",
      solution: "SehatRx listens to the consultation, transcribes it in real time using Whisper, drafts a structured prescription via LLM, and delivers it to the patient's portal the moment the doctor approves — zero paperwork, zero delay.",
      whyAIHeadline: "Without AI, this workflow simply can't exist.",
      whyAI: "Real-time speech transcription, multilingual support (Hindi + English code-switching), and extracting diagnosis/medications/dosage from free-form speech are all AI-native problems. A rule-based system can't handle natural conversation. AI is the product, not a feature.",
      tradeoffs: [
        { title: "Whisper (cloud) vs. on-device STT", body: "Whisper gives significantly better accuracy on Hindi-English code-switching than on-device alternatives. The tradeoff is latency and cost per transcription — acceptable for a clinical setting where accuracy is non-negotiable." },
        { title: "LLM prescription drafting vs. structured form input", body: "Free-form speech → LLM structuring is faster for doctors but introduces hallucination risk on medication names. Mitigated by requiring doctor review before any prescription is finalized." },
        { title: "JWT auth vs. OAuth", body: "JWT keeps the backend stateless and avoids third-party OAuth dependency for a clinic-facing product where patients may not have Google accounts. The tradeoff is manual token refresh management." },
      ],
    },
  },
  {
    href: "https://github.com/akshita270/askql",
    live: "https://lnkd.in/gabgdR3i",
    title: "AskQL — Multi-Tenant Text-to-SQL Analytics Platform",
    description:
      "Ask questions about your data in plain English and get back a live SQL query, results table, and auto-generated chart — no SQL knowledge required. A full-stack, multi-tenant platform where each user gets an isolated workspace for their own CSV datasets alongside a shared demo database.",
    thumbnail: "🗄️",
    image: "/images/projects/askql.png",
    contain: true,
    color: "#6366f1",
    period: "2026",
    stack: ["FastAPI", "React", "PostgreSQL", "SQLite", "Google Cloud Run", "GCS", "Vercel", "OpenAI"],
    slug: "askql",
    featured: true,
    deck: "/AskQL-Deck.pdf",
    highlights: [
      "Multi-tenant architecture: each user gets an isolated workspace for uploading CSV datasets alongside a shared demo database",
      "Backend streams generated SQL token-by-token in real time with an AST-based guardrail layer that blocks unauthorized tables, non-SELECT statements, and prompt-injection attempts before any query touches the database",
      "Auto-generated charts rendered from query results — no configuration needed",
      "Internal observability dashboard tracking live usage, cost, and SQL accuracy against a golden evaluation set",
      "Deployed end-to-end: Vercel (frontend), Google Cloud Run (backend), Supabase Postgres, and GCS for durable per-user file persistence",
    ],
    caseStudy: {
      problemHeadline: "Most people can't query their own data — SQL is a barrier.",
      problem: "Business teams sit on valuable data but depend on engineers to write SQL every time they have a question. It slows decisions, creates bottlenecks, and means most data never gets explored at all.",
      solutionHeadline: "Ask a question in English. Get a live SQL query, results, and a chart.",
      solution: "AskQL translates natural language into SQL in real time, streams the query token-by-token, runs it against the user's own isolated dataset, and auto-generates a chart — no SQL knowledge required, no configuration needed.",
      whyAIHeadline: "Natural language → SQL translation is an LLM-native problem.",
      whyAI: "Mapping intent from free-form English to syntactically correct, context-aware SQL across arbitrary schemas is exactly what LLMs excel at. A rule-based approach would require hand-coding every query pattern — AI makes it generalize across any dataset a user uploads.",
      tradeoffs: [
        { title: "LLM-generated SQL vs. pre-built query builder", body: "A visual query builder would be safer but far less flexible — users couldn't express complex joins or aggregations without SQL knowledge anyway. LLM generation handles the full range of questions at the cost of needing a guardrail layer." },
        { title: "AST-based guardrails vs. prompt-only safety", body: "Relying solely on prompt instructions to block unsafe SQL is too fragile for a multi-tenant product. An AST parser that blocks non-SELECT statements and cross-tenant table access before the query touches the database is the only safe approach." },
        { title: "Per-user SQLite vs. shared Postgres", body: "Isolating each user's uploaded CSVs into their own SQLite instance prevents any cross-tenant data leakage without row-level security complexity. The tradeoff is that joins across a user's personal data and the shared demo DB require a query routing layer." },
      ],
    },
  },
  {
    href: "https://github.com/akshita270/startup-copilot",
    title: "Startup Copilot",
    description:
      "An AI co-pilot that generates a complete startup blueprint in minutes using a 7-agent pipeline — idea generation, market research, competitor analysis, revenue modeling, MVP planning, and an investor-ready pitch deck, fully automated.",
    thumbnail: "🚀",
    image: "/images/projects/startup-copilot.png",
    color: "#8b5cf6",
    period: "2026",
    stack: ["Python", "FastAPI", "React", "Vite", "Groq (Llama 3.3-70B)", "Supabase"],
    slug: "startup-copilot",
    featured: true,
    live: "https://startup-copilot-ohe44n0s9-akshita270s-projects.vercel.app",
    blog: "https://tinyurl.com/379j7j5v",
    highlights: [
      "7 sequential agents: Idea Generation → Market Research → Competitor Analysis → Revenue Model → MVP Planner → Synthesis → Pitch Generator",
      "Idea Generation produces 4 startup concepts with name, tagline, problem, target user, and UVP; Market Research adds TAM/SAM/SOM and customer personas",
      "Competitor Analysis surfaces 4-5 real competitors with gap analysis and positioning strategy",
      "MVP Planner outputs core features, tech stack, and a 12-week build timeline; Synthesis produces an executive summary and startup score",
      "Final agent generates an 11-slide pitch deck outline with speaker notes, auto-converted to a downloadable .pptx via python-pptx",
      "Live SSE streaming of pipeline progress to a React frontend, backed by Supabase for run history",
    ],
    caseStudy: {
      problemHeadline: "Founders waste weeks on work that shouldn't take weeks.",
      problem: "Market sizing, competitor research, revenue modeling, pitch decks — each is slow and repetitive, not hard. Most founders either skip them and walk into investor meetings underprepared, or pay consultants for boilerplate output.",
      solutionHeadline: "One idea → 7 agents → full startup blueprint in minutes.",
      solution: "Each agent owns one piece of the blueprint and passes its output to the next. The user types an idea; minutes later they have market research, competitor gaps, a revenue model, MVP roadmap, executive summary, and a downloadable pitch deck.",
      whyAIHeadline: "This product category only exists because of AI.",
      whyAI: "Every output follows patterns an LLM trained on thousands of business documents can reproduce in seconds. Without AI, this requires either a team of analysts or a founder spending nights on tasks that aren't their core skill. AI doesn't just speed it up — it makes the whole thing possible for a solo builder.",
      tradeoffs: [
        { title: "Sequential vs. parallel agents", body: "Agents run in sequence so each one's output feeds the next — the revenue model knows what market research found. Parallel would be faster but loses that cross-agent context." },
        { title: "Groq (Llama 3.3-70B) vs. GPT-4", body: "Groq is significantly faster for structured business writing, but has tighter rate limits across 7 back-to-back LLM calls." },
        { title: "Fixed pipeline vs. dynamic routing", body: "Always runs all 7 agents in order. Simpler to debug and keeps output format predictable — which matters when the PPTX generator needs to parse structured sections." },
      ],
    },
  },
  {
    href: "https://github.com/akshita270/GeneSight",
    title: "GeneSight – Genomic Intelligence Pipeline",
    description:
      "An agentic AI system that automatically generates scientific hypotheses from genomics literature and biological databases using an 8-agent pipeline — from literature retrieval to knowledge graph construction and evidence-validated hypothesis generation.",
    thumbnail: "🧬",
    image: "/images/projects/genesight.png",
    color: "#06b6d4",
    period: "2026",
    stack: ["Python", "FastAPI", "GPT-4o", "Neo4j", "spaCy", "Streamlit"],
    slug: "genesight",
    featured: true,
    highlights: [
      "8-agent pipeline: Task Planner → Literature Retrieval (PubMed/NCBI Entrez) → Info Extraction (spaCy biomedical NER) → Genomics DB lookup (NCBI Gene + UniProt) → Knowledge Graph (Neo4j) → Hypothesis Generation (GPT-4o) → Evidence Validation → Report Generation",
      "Pulls real biomedical literature from PubMed and cross-references NCBI Gene and UniProt for gene/protein metadata",
      "Builds a persistent knowledge graph in Neo4j linking genes, diseases, and supporting evidence",
      "Ranks generated hypotheses by confidence score with supporting evidence attached — e.g. querying \"new gene relationships related to Alzheimer's disease\" returns ranked, evidence-backed hypotheses",
      "FastAPI backend with async job polling (`/query`, `/status/{job_id}`, `/result/{job_id}`) and a Streamlit front-end",
    ],
    caseStudy: {
      problemHeadline: "Scientific hypothesis generation takes researchers months — most leads never get explored.",
      problem: "Biomedical researchers manually scan thousands of papers, cross-reference gene databases, and piece together evidence before forming a single hypothesis. Most promising gene-disease connections are never explored simply because the process doesn't scale.",
      solutionHeadline: "Type a query. Get ranked, evidence-backed hypotheses in minutes.",
      solution: "An 8-agent pipeline retrieves real literature from PubMed, extracts biomedical entities with spaCy NER, cross-references NCBI Gene and UniProt, builds a knowledge graph in Neo4j, generates hypotheses with GPT-4o, and validates them against evidence — all automatically.",
      whyAIHeadline: "No rule-based system can read papers, extract meaning, and reason across a knowledge graph.",
      whyAI: "Biomedical NER, literature comprehension, and hypothesis generation from sparse evidence are all tasks that require deep language understanding. GPT-4o reasons across the knowledge graph to surface connections a keyword search would never find. AI doesn't assist the pipeline — it is the pipeline.",
      tradeoffs: [
        { title: "GPT-4o vs. biomedical fine-tuned models", body: "GPT-4o's general reasoning outperforms smaller domain-specific models on cross-domain hypothesis generation. The tradeoff is cost and latency per query — acceptable for a research tool where quality matters more than speed." },
        { title: "Neo4j knowledge graph vs. vector similarity search", body: "A graph database captures explicit gene-disease-evidence relationships and supports multi-hop queries. Vector search would be faster for retrieval but loses the structured relationship semantics that make hypothesis validation meaningful." },
        { title: "8-agent sequential pipeline vs. single LLM call", body: "Each agent specializes in one task — retrieval, extraction, graph construction, generation, validation — producing far more accurate output than asking one prompt to do everything. The cost is pipeline latency and complexity." },
      ],
    },
  },
  {
    href: "https://github.com/akshita270/RAG-comparison-experiment",
    title: "RAG Comparison Experiment",
    description:
      "A structured research experiment comparing four RAG architectures — Vanilla, HyDE, GraphRAG, and Agentic RAG — on their ability to reduce hallucinations when answering questions about AI/ML research papers from ArXiv.",
    thumbnail: "📚",
    image: "/images/projects/rag-comparison-experiment.jpg",
    color: "#10b981",
    period: "2026",
    stack: ["Python", "ChromaDB", "RAGAS", "Claude/GPT", "LLM-as-Judge"],
    slug: "rag-comparison-experiment",
    research: true,
    live: "https://huggingface.co/spaces/akshita27/RAG-comparison-dashboard",
    blog: "https://tinyurl.com/3jyjvhaz",
    highlights: [
      "4 architectures benchmarked head-to-head: Vanilla RAG (baseline), HyDE RAG (hypothetical-document embeddings), GraphRAG (knowledge graph + vector hybrid), and Agentic RAG (ReAct tool-use agent)",
      "Each architecture answers the same 25 questions over the same 25 ArXiv papers — 100 LLM answer calls total, plus ~200 scoring calls",
      "Evaluated on faithfulness, relevance, context precision, and latency using RAGAS metrics and a blind LLM-as-judge (1–5 scoring)",
      "Produces a results CSV and 4 comparison charts to identify which retrieval strategy actually reduces hallucination in production RAG systems",
    ],
    caseStudy: {
      problemHeadline: "Everyone builds RAG — nobody measures which architecture actually works.",
      problem: "Most RAG systems are shipped without rigorous benchmarking. Teams choose Vanilla RAG or HyDE or GraphRAG based on intuition, blog posts, or what's easiest to implement — not data. There's no controlled comparison showing which approach actually reduces hallucinations.",
      solutionHeadline: "Four architectures, same 25 questions, same papers — let the metrics decide.",
      solution: "Each architecture answers the same 25 questions over 25 ArXiv papers. RAGAS measures faithfulness, relevance, and context precision. A blind LLM-as-judge scores 1–5. Results go into a CSV and 4 comparison charts, giving a clear answer on what works and what doesn't.",
      whyAIHeadline: "Only an LLM can judge whether an LLM answer is faithful to its sources.",
      whyAI: "Traditional metrics can't assess whether a generated answer is grounded in retrieved context. LLM-as-judge uses the same kind of language understanding as the system under test to score faithfulness — it's the only automated evaluation method that catches the hallucinations that matter.",
      tradeoffs: [
        { title: "LLM-as-judge vs. RAGAS-only evaluation", body: "RAGAS gives automated, reproducible scores but can miss nuanced hallucinations. A blind LLM judge adds human-like quality scoring but costs more and introduces model-specific bias. Both together give a fuller picture." },
        { title: "Agentic RAG vs. GraphRAG", body: "Agentic RAG scores higher on complex multi-hop questions by dynamically deciding what to retrieve next. GraphRAG wins on structured relational questions. Neither dominates — the best architecture depends on the query type." },
        { title: "Fixed 25-question eval set vs. larger benchmark", body: "25 questions keeps compute cost manageable (300+ LLM calls total) while still producing statistically meaningful comparisons. A larger set would increase confidence but at 10x the cost — diminishing returns for a research experiment." },
      ],
      results: [
        { value: "0.980", label: "Faithfulness", sub: "HyDE RAG wins" },
        { value: "0.960", label: "Answer Relevancy", sub: "HyDE RAG wins" },
        { value: "0.832", label: "Context Precision", sub: "HyDE RAG wins" },
        { value: "4.120", label: "Judge Factuality", sub: "HyDE RAG wins" },
        { value: "4.440", label: "Judge Relevance", sub: "Vanilla RAG wins" },
        { value: "4.120", label: "Judge Citation", sub: "Vanilla RAG wins" },
        { value: "2460ms", label: "Latency", sub: "Vanilla RAG — fastest" },
      ],
    },
  },
  {
    href: "https://github.com/akshita270/-ReflexRAG",
    title: "ReflexRAG",
    description:
      "A production-grade RAG system for clinical research PDFs, combining hybrid retrieval, cross-encoder reranking, and a dual self-reflection grading loop that validates both retrieval quality and answer faithfulness before returning a response.",
    thumbnail: "🔁",
    image: "/images/projects/reflexrag.png",
    color: "#ec4899",
    period: "2026",
    stack: ["Python", "FastAPI", "FAISS", "BM25", "Next.js", "GPT-4o mini"],
    slug: "reflexrag",
    live: "https://reflexrag.netlify.app",
    highlights: [
      "9-stage pipeline: PDF load/clean → sentence chunking → FAISS + BM25 hybrid indexing → Reciprocal Rank Fusion → MMR diversity filtering → cross-encoder reranking → retrieval grading → GPT-4o mini generation → answer grading",
      "Two self-reflection checkpoints: a retrieval grader and an answer grader, each retrying with query expansion if validation fails",
      "Rule-based table parser accurately extracts structured data from clinical tables (e.g. cardiac murmur characteristics) instead of mangling them in plain-text chunks",
      "Session-scoped, in-memory FAISS index per PDF upload — no shared state between users",
      "Deployed live on AWS EC2 with a Next.js + Tailwind frontend on Netlify",
    ],
    caseStudy: {
      problemHeadline: "Standard RAG hallucinates — and has no way to know it's wrong.",
      problem: "Vanilla RAG retrieves chunks and generates an answer in one shot. If the retrieved context is irrelevant or the answer is unfaithful, the system returns it anyway. For clinical research documents where accuracy is non-negotiable, that's a hard failure.",
      solutionHeadline: "A 9-stage pipeline that validates itself before returning anything.",
      solution: "ReflexRAG uses hybrid retrieval (FAISS + BM25), cross-encoder reranking, and two self-reflection checkpoints — a retrieval grader and an answer grader — each triggering query expansion and retry if validation fails. Nothing is returned until both checks pass.",
      whyAIHeadline: "Self-reflection grading is only possible because LLMs can evaluate their own outputs.",
      whyAI: "The retrieval grader and answer grader both use GPT-4o mini to score quality and faithfulness — a task that requires language understanding, not just pattern matching. Without LLM-as-judge, there's no reliable automated way to catch hallucinations before they reach the user.",
      tradeoffs: [
        { title: "Hybrid retrieval vs. dense-only (FAISS)", body: "BM25 catches exact keyword matches that dense embeddings miss — critical for clinical terms and drug names. The tradeoff is added index complexity and the need for Reciprocal Rank Fusion to merge the two result sets." },
        { title: "Self-reflection retry vs. single-pass generation", body: "Retrying on failed grading adds latency (up to 2 extra LLM calls per query). For a clinical use case, the accuracy gain is worth it — a wrong answer with confidence is worse than a slower correct one." },
        { title: "Session-scoped in-memory index vs. persistent shared index", body: "Each PDF upload gets its own FAISS index in memory, so there's zero cross-user data leakage. The tradeoff is that the index is lost on session end — fine for a research tool, not for a persistent knowledge base." },
      ],
    },
  },
  {
    href: "https://github.com/akshita270/memoryos-benchmark",
    live: "https://huggingface.co/spaces/akshita27/memoryos-benchmark",
    title: "MemoryOS Benchmark",
    description:
      "A controlled benchmark proving that an AI agent with a 3-layer memory system consistently outperforms a stateless baseline across 50 scripted tasks spanning 10 sessions — quantifying exactly how much persistent memory improves an agent.",
    thumbnail: "🧠",
    image: "/images/projects/memoryos-benchmark.png",
    color: "#f59e0b",
    period: "2026",
    stack: ["Python", "OpenAI API", "ChromaDB", "Agentic AI"],
    slug: "memoryos-benchmark",
    research: true,
    highlights: [
      "3-layer memory architecture: working memory (in-session, cleared each session), episodic memory (ChromaDB, semantic search over past messages), and semantic memory (LLM-compressed long-term user profile)",
      "A deterministic MemoryRouter combines all three layers before every LLM call — no LLM calls inside the router itself",
      "Benchmarked against a stateless baseline agent across 50 tasks following a fictional user whose facts are introduced early and must be recalled and synthesized later",
      "Memory-equipped agent's score diverges clearly from the stateless baseline by session 4, reaching near-perfect scores on complex synthesis tasks by sessions 7–10",
    ],
    caseStudy: {
      problemHeadline: "AI agents forget everything between sessions — the same questions get answered from scratch every time.",
      problem: "Stateless agents have no continuity. Every session starts cold — no memory of what the user said last week, no learned preferences, no ability to synthesize facts across conversations. This limits agents to single-session tasks and makes them feel dumb compared to a human assistant.",
      solutionHeadline: "A 3-layer memory system that proves persistent memory makes agents measurably smarter.",
      solution: "Working memory handles in-session context. Episodic memory (ChromaDB) semantically retrieves past conversations. Semantic memory compresses long-term user facts into a profile. A deterministic MemoryRouter combines all three before every LLM call — benchmarked against a stateless baseline across 50 tasks.",
      whyAIHeadline: "Memory only matters if the AI can reason across what it remembers — not just retrieve it.",
      whyAI: "Retrieving a past message isn't enough. The agent needs to synthesize across multiple episodic memories and an evolving user profile to answer questions like 'based on everything I've told you, what should I focus on?' That kind of cross-memory reasoning requires LLM-level language understanding.",
      tradeoffs: [
        { title: "Semantic memory compression vs. full history retrieval", body: "Compressing long-term facts into a user profile keeps the context window manageable and forces the LLM to reason over a clean summary. Full history retrieval would be more complete but creates a bloated, noisy context that degrades answer quality." },
        { title: "Deterministic MemoryRouter vs. LLM-based routing", body: "A deterministic router is predictable, fast, and makes the benchmark reproducible — the same query always pulls the same memory layers. An LLM router could be smarter but would add latency and make results harder to attribute." },
        { title: "ChromaDB for episodic memory vs. keyword search", body: "Semantic similarity retrieval finds relevant past conversations even when exact words don't match — essential for a memory system. Keyword search would miss paraphrased references to earlier facts." },
      ],
    },
  },
  {
    href: "https://github.com/akshita270/devassist-workspace",
    title: "DevAssist — Personal Dev Workspace MCP Server",
    description:
      "A Model Context Protocol (MCP) server that connects Claude to a local dev workspace — managing tasks, searching notes, syncing GitHub issues, and visualizing everything in a web dashboard. Implements all 3 MCP primitives: Tools, Resources, and Prompts.",
    thumbnail: "🛠️",
    image: "/images/projects/devassist-workspace.svg",
    color: "#8b5cf6",
    period: "2026",
    stack: ["Python", "FastMCP", "FastAPI", "SQLite", "GitHub REST API"],
    slug: "devassist-workspace",
    highlights: [
      "13 MCP tools spanning task management (create/complete/delete/list tasks, notes search) and GitHub integration (list/create/close issues, link tasks to issues, sync issues as local tasks)",
      "Implements all 3 MCP primitives: Tools (callable functions), Resources (read-only data like devassist://tasks and devassist://notes/{filename}), and Prompts (reusable templates like daily_standup and project_brief)",
      "SQLite-backed task and note storage, with markdown notes exposed directly as MCP Resources",
      "FastAPI + vanilla JS web dashboard for live task management, GitHub issue sync, and notes overview alongside the MCP server",
      "Drops straight into Claude Desktop/Claude Code via claude_desktop_config.json — talk to it naturally: \"Create a task: set up CI/CD, high priority\" or \"Give me my daily standup\"",
    ],
    caseStudy: {
      problemHeadline: "Developers context-switch constantly — tasks, notes, GitHub, and Claude are all separate tools.",
      problem: "Every time a developer needs to check tasks, search notes, or sync a GitHub issue, they leave their flow. Claude can answer questions but can't touch your local workspace. The gap between AI and your actual dev environment is manual copy-paste.",
      solutionHeadline: "Claude connects directly to your dev workspace — tasks, notes, and GitHub in one conversation.",
      solution: "DevAssist is an MCP server that gives Claude 13 tools to manage tasks, search markdown notes, sync GitHub issues, and surface everything in a live web dashboard. Ask Claude for your daily standup or to create a high-priority task — it just works.",
      whyAIHeadline: "Natural language task and project management is only useful when the AI can actually act on your workspace.",
      whyAI: "The value isn't answering questions about your project — it's Claude being able to create a task, close a GitHub issue, or draft a standup from your real data, without you leaving the conversation. MCP makes Claude an agent in your environment, not just a chatbot next to it.",
      tradeoffs: [
        { title: "FastMCP vs. raw MCP SDK", body: "FastMCP drastically reduces boilerplate for defining tools, resources, and prompts. The tradeoff is a thin abstraction layer over the raw SDK — acceptable since MCP's spec is stable and FastMCP tracks it closely." },
        { title: "SQLite vs. file-based task storage", body: "SQLite gives structured querying and task-issue linking without a server dependency. Plain files would be simpler but can't support the relational queries needed to link tasks to GitHub issues." },
        { title: "Local MCP server vs. cloud-hosted agent", body: "Running locally means zero latency, no auth complexity, and full access to the filesystem for notes. A cloud-hosted version would be shareable across machines but loses the local-first simplicity that makes the setup a single config file." },
      ],
    },
  },
  {
    href: "https://github.com/akshita270/financial-agent",
    title: "Financial AI Agent",
    description:
      "An autonomous multi-agent system for financial data analysis — one agent pulls live stock prices, fundamentals, and analyst recommendations while a second searches the web for the latest market news, with a Streamlit UI to query both at once.",
    thumbnail: "📈",
    image: "/images/projects/financial-agent.svg",
    contain: false,
    color: "#10b981",
    period: "2025",
    live: "https://financial-agent-9mqzctk8pzyj3vbaxdz26t.streamlit.app",
    stack: ["Python", "Streamlit", "Phidata", "GPT-4o mini", "yfinance"],
    slug: "financial-agent",
    highlights: [
      "Two-agent team: a Finance Agent (yfinance tools for stock price, fundamentals, and analyst recommendations) and a Web Search Agent (DuckDuckGo for the latest financial news), each backed by GPT-4o mini",
      "Agents stay in their lane by design — the web agent is explicitly instructed not to fetch stock prices, leaving that strictly to the finance agent's tool calls",
      "Finance Agent renders results as markdown tables for clean side-by-side comparison",
      "Streamlit interface takes any stock, company, or financial question and runs both agents in parallel, showing market data and news side by side",
    ],
    caseStudy: {
      problemHeadline: "Financial analysis means juggling live market data and breaking news at the same time — no single tool does both well.",
      problem: "Stock screeners give numbers but no context. News tools give headlines but no data. An analyst needs both simultaneously — live fundamentals alongside the news story driving a price move — and manually switching between tools loses the connection between them.",
      solutionHeadline: "Two specialized agents working in parallel — one on data, one on news.",
      solution: "A Finance Agent pulls live stock prices, fundamentals, and analyst recommendations via yfinance tools. A Web Search Agent finds the latest market news via DuckDuckGo. Both are backed by GPT-4o mini, run in parallel on any query, and surface results side by side in a Streamlit interface.",
      whyAIHeadline: "Only an LLM can connect a raw earnings number to the news story that explains why it moved the stock.",
      whyAI: "Fetching data is trivial. Interpreting what a P/E ratio means in the context of this week's Fed decision, or why a stock dropped despite good earnings — that requires reasoning over both structured data and unstructured news. GPT-4o mini bridges the two in natural language.",
      tradeoffs: [
        { title: "Two specialized agents vs. one general agent", body: "Keeping agents in their lane prevents the web agent from hallucinating stock prices (a known failure mode) and keeps tool use clean. A single agent would be simpler but harder to constrain — financial accuracy is non-negotiable." },
        { title: "GPT-4o mini vs. GPT-4o", body: "GPT-4o mini is significantly cheaper for the high-volume tool calls this system makes (price lookups, news searches, fundamentals) with minimal quality loss on structured financial tasks. GPT-4o would add cost without meaningful accuracy gains here." },
        { title: "DuckDuckGo search vs. financial news API", body: "DuckDuckGo requires no API key and covers a broad range of sources. A dedicated financial news API (Bloomberg, Benzinga) would give higher-quality, structured results but adds cost and setup friction for a research prototype." },
      ],
    },
  },
  {
    href: "https://github.com/akshita270/speculative-decoding-inference-engine",
    live: "https://speculative-decoding-inference-engine.streamlit.app",
    title: "Speculative Decoding Inference Engine",
    description:
      "A mini LLM inference system built around speculative decoding — a small draft model proposes tokens ahead, and a large target model verifies them in a single batched pass, producing mathematically identical output to standard sampling but significantly faster.",
    thumbnail: "⚡",
    image: "/images/projects/spec-decoding.webp",
    contain: false,
    color: "#6366f1",
    period: "2026",
    stack: ["Python", "FastAPI", "Streamlit", "HuggingFace", "PyTorch"],
    slug: "speculative-decoding-inference-engine",
    highlights: [
      "Speculative decoding engine: draft model proposes k tokens, target model verifies all in one batched forward pass — accept/reject rule guarantees output is mathematically identical to sampling from the target alone",
      "Request queue + batcher groups concurrent requests arriving within ~50ms into a single batch instead of dropping them",
      "Semantic cache layer: cosine similarity ≥ 0.92 serves cached responses instantly, bypassing the inference engine entirely",
      "Load-based router: routes to a faster draft model under high load, a better draft model under low load — balancing latency vs. acceptance rate dynamically",
    ],
    caseStudy: {
      problemHeadline: "LLM inference is slow — and most optimization techniques sacrifice output quality to get speed.",
      problem: "Standard autoregressive sampling generates one token at a time. Techniques like quantization or smaller models speed things up but change the output distribution. There's no free lunch — until speculative decoding, which gets the speed without touching the quality.",
      solutionHeadline: "A small draft model proposes tokens. The large model verifies them all in one pass.",
      solution: "The draft model speculatively generates k tokens ahead. The target model verifies all k in a single batched forward pass using an accept/reject rule that guarantees output is mathematically identical to sampling from the target alone — faster inference, zero quality loss. A semantic cache and load-based router further reduce redundant compute.",
      whyAIHeadline: "Speculative decoding only works because large and small models share the same token distribution.",
      whyAI: "The acceptance rate — how many draft tokens the target model keeps — depends entirely on the draft and target models being trained on similar data. A random heuristic guesser would have near-zero acceptance. The technique is uniquely enabled by the way language models are trained, not a general-purpose optimization trick.",
      tradeoffs: [
        { title: "Speculative decoding vs. quantization for speed", body: "Quantization changes model weights and shifts the output distribution — faster, but not identical output. Speculative decoding is mathematically lossless: the accept/reject rule proves output is identical to the target model alone. Better for quality-sensitive applications." },
        { title: "Semantic cache vs. exact-match cache", body: "Cosine similarity ≥ 0.92 catches paraphrased repeats of the same question and serves cached responses instantly. Exact-match cache misses these. The tradeoff is a small risk of serving a cached answer to a subtly different query." },
        { title: "Load-based draft model routing vs. fixed draft model", body: "Routing between a faster and a better draft model based on queue depth dynamically trades acceptance rate for throughput under load. A fixed draft model is simpler to reason about but leaves latency on the table during low-traffic periods." },
      ],
      results: [
        { value: "70%", label: "Cache Hit Rate", sub: "Semantic cache ≥ 0.92 cosine sim" },
        { value: "48.4%", label: "Draft Acceptance Rate", sub: "gpt2 + gpt2-medium ensemble" },
        { value: "340", label: "Requests Served", sub: "0 fallbacks — 100% reliability" },
        { value: "~1s", label: "p50 Latency", sub: "p95 at 40s under max load" },
      ],
    },
  },
];
