export const products = [
  {
    href: "https://github.com/akshita270/GeneSight",
    title: "GeneSight – Genomic Intelligence Pipeline",
    description:
      "An agentic AI system that automatically generates scientific hypotheses from genomics literature and biological databases using an 8-agent pipeline — from literature retrieval to knowledge graph construction and evidence-validated hypothesis generation.",
    thumbnail: "🧬",
    image: "/images/projects/genesight.png",
    color: "#06b6d4",
    period: "2026",
    stack: ["Python", "FastAPI", "GPT-4o", "Neo4j", "spaCy", "Streamlit"],
    slug: "genesight",
    highlights: [
      "8-agent pipeline: Task Planner → Literature Retrieval (PubMed/NCBI Entrez) → Info Extraction (spaCy biomedical NER) → Genomics DB lookup (NCBI Gene + UniProt) → Knowledge Graph (Neo4j) → Hypothesis Generation (GPT-4o) → Evidence Validation → Report Generation",
      "Pulls real biomedical literature from PubMed and cross-references NCBI Gene and UniProt for gene/protein metadata",
      "Builds a persistent knowledge graph in Neo4j linking genes, diseases, and supporting evidence",
      "Ranks generated hypotheses by confidence score with supporting evidence attached — e.g. querying \"new gene relationships related to Alzheimer's disease\" returns ranked, evidence-backed hypotheses",
      "FastAPI backend with async job polling (`/query`, `/status/{job_id}`, `/result/{job_id}`) and a Streamlit front-end",
    ],
  },
  {
    href: "https://github.com/akshita270/startup-copilot",
    title: "Startup Copilot",
    description:
      "An AI co-pilot that generates a complete startup blueprint in minutes using a 7-agent pipeline — idea generation, market research, competitor analysis, revenue modeling, MVP planning, and an investor-ready pitch deck, fully automated.",
    thumbnail: "🚀",
    image: "/images/projects/startup-copilot.png",
    color: "#8b5cf6",
    period: "2026",
    stack: ["Python", "FastAPI", "React", "Vite", "Groq (Llama 3.3-70B)", "Supabase"],
    slug: "startup-copilot",
    live: "https://startup-copilot-ohe44n0s9-akshita270s-projects.vercel.app",
    blog: "https://tinyurl.com/379j7j5v",
    highlights: [
      "7 sequential agents: Idea Generation → Market Research → Competitor Analysis → Revenue Model → MVP Planner → Synthesis → Pitch Generator",
      "Idea Generation produces 4 startup concepts with name, tagline, problem, target user, and UVP; Market Research adds TAM/SAM/SOM and customer personas",
      "Competitor Analysis surfaces 4-5 real competitors with gap analysis and positioning strategy",
      "MVP Planner outputs core features, tech stack, and a 12-week build timeline; Synthesis produces an executive summary and startup score",
      "Final agent generates an 11-slide pitch deck outline with speaker notes, auto-converted to a downloadable .pptx via python-pptx",
      "Live SSE streaming of pipeline progress to a React frontend, backed by Supabase for run history",
    ],
  },
  {
    href: "https://github.com/akshita270/RAG-comparison-experiment",
    title: "RAG Comparison Experiment",
    description:
      "A structured research experiment comparing four RAG architectures — Vanilla, HyDE, GraphRAG, and Agentic RAG — on their ability to reduce hallucinations when answering questions about AI/ML research papers from ArXiv.",
    thumbnail: "📚",
    image: "/images/projects/rag-comparison-experiment.jpg",
    color: "#10b981",
    period: "2026",
    stack: ["Python", "ChromaDB", "RAGAS", "Claude/GPT", "LLM-as-Judge"],
    slug: "rag-comparison-experiment",
    research: true,
    live: "https://huggingface.co/spaces/akshita27/RAG-comparison-dashboard",
    blog: "https://tinyurl.com/3jyjvhaz",
    highlights: [
      "4 architectures benchmarked head-to-head: Vanilla RAG (baseline), HyDE RAG (hypothetical-document embeddings), GraphRAG (knowledge graph + vector hybrid), and Agentic RAG (ReAct tool-use agent)",
      "Each architecture answers the same 25 questions over the same 25 ArXiv papers — 100 LLM answer calls total, plus ~200 scoring calls",
      "Evaluated on faithfulness, relevance, context precision, and latency using RAGAS metrics and a blind LLM-as-judge (1–5 scoring)",
      "Produces a results CSV and 4 comparison charts to identify which retrieval strategy actually reduces hallucination in production RAG systems",
    ],
  },
  {
    href: "https://github.com/akshita270/-ReflexRAG",
    title: "ReflexRAG",
    description:
      "A production-grade RAG system for clinical research PDFs, combining hybrid retrieval, cross-encoder reranking, and a dual self-reflection grading loop that validates both retrieval quality and answer faithfulness before returning a response.",
    thumbnail: "🔁",
    image: "/images/projects/reflexrag.png",
    color: "#ec4899",
    period: "2026",
    stack: ["Python", "FastAPI", "FAISS", "BM25", "Next.js", "GPT-4o mini"],
    slug: "reflexrag",
    live: "https://reflexrag.netlify.app",
    highlights: [
      "9-stage pipeline: PDF load/clean → sentence chunking → FAISS + BM25 hybrid indexing → Reciprocal Rank Fusion → MMR diversity filtering → cross-encoder reranking → retrieval grading → GPT-4o mini generation → answer grading",
      "Two self-reflection checkpoints: a retrieval grader and an answer grader, each retrying with query expansion if validation fails",
      "Rule-based table parser accurately extracts structured data from clinical tables (e.g. cardiac murmur characteristics) instead of mangling them in plain-text chunks",
      "Session-scoped, in-memory FAISS index per PDF upload — no shared state between users",
      "Deployed live on AWS EC2 with a Next.js + Tailwind frontend on Netlify",
    ],
  },
  {
    href: "https://github.com/akshita270/memoryos-benchmark",
    live: "https://huggingface.co/spaces/akshita27/memoryos-benchmark",
    title: "MemoryOS Benchmark",
    description:
      "A controlled benchmark proving that an AI agent with a 3-layer memory system consistently outperforms a stateless baseline across 50 scripted tasks spanning 10 sessions — quantifying exactly how much persistent memory improves an agent.",
    thumbnail: "🧠",
    image: "/images/projects/memoryos-benchmark.png",
    color: "#f59e0b",
    period: "2026",
    stack: ["Python", "OpenAI API", "ChromaDB", "Agentic AI"],
    slug: "memoryos-benchmark",
    research: true,
    highlights: [
      "3-layer memory architecture: working memory (in-session, cleared each session), episodic memory (ChromaDB, semantic search over past messages), and semantic memory (LLM-compressed long-term user profile)",
      "A deterministic MemoryRouter combines all three layers before every LLM call — no LLM calls inside the router itself",
      "Benchmarked against a stateless baseline agent across 50 tasks following a fictional user whose facts are introduced early and must be recalled and synthesized later",
      "Memory-equipped agent's score diverges clearly from the stateless baseline by session 4, reaching near-perfect scores on complex synthesis tasks by sessions 7–10",
    ],
  },
  {
    href: "https://github.com/akshita270/voicesql",
    title: "VoiceSQL",
    description:
      "Upload any CSV and ask questions about it in plain English — by voice or text. VoiceSQL transcribes the question, generates SQL, executes it, verifies the answer for accuracy, and renders a chart in one seamless flow.",
    thumbnail: "🎙️",
    image: "/images/projects/voicesql.png",
    color: "#6366f1",
    period: "2026",
    stack: ["Python", "faster-whisper", "GPT-4o", "DuckDB", "Streamlit"],
    slug: "voicesql",
    live: "https://akshita27-voicesql.hf.space",
    highlights: [
      "Pipeline: ASR (faster-whisper) → intent rewriting (GPT-4o-mini) → semantic cache lookup → text-to-SQL (GPT-4o) → SQL validation (sqlglot) → DuckDB execution → hallucination guard → chart + narrated answer",
      "Semantic caching embeds each resolved question and matches it against past questions in the session (cosine similarity ≥ 0.93), skipping redundant SQL/narration calls for paraphrased repeats",
      "Model tiering keeps cost down: GPT-4o-mini handles simple rewriting/narration, GPT-4o is reserved for real text-to-SQL reasoning",
      "Custom hallucination guard cross-checks every number in the narrated answer against the actual DB result before returning it",
      "Remembers the last 6 conversation turns for natural follow-up questions",
    ],
  },
  {
    href: "https://github.com/akshita270/devassist-workspace",
    title: "DevAssist — Personal Dev Workspace MCP Server",
    description:
      "A Model Context Protocol (MCP) server that connects Claude to a local dev workspace — managing tasks, searching notes, syncing GitHub issues, and visualizing everything in a web dashboard. Implements all 3 MCP primitives: Tools, Resources, and Prompts.",
    thumbnail: "🛠️",
    image: "/images/projects/devassist-workspace.svg",
    color: "#8b5cf6",
    period: "2026",
    stack: ["Python", "FastMCP", "FastAPI", "SQLite", "GitHub REST API"],
    slug: "devassist-workspace",
    highlights: [
      "13 MCP tools spanning task management (create/complete/delete/list tasks, notes search) and GitHub integration (list/create/close issues, link tasks to issues, sync issues as local tasks)",
      "Implements all 3 MCP primitives: Tools (callable functions), Resources (read-only data like devassist://tasks and devassist://notes/{filename}), and Prompts (reusable templates like daily_standup and project_brief)",
      "SQLite-backed task and note storage, with markdown notes exposed directly as MCP Resources",
      "FastAPI + vanilla JS web dashboard for live task management, GitHub issue sync, and notes overview alongside the MCP server",
      "Drops straight into Claude Desktop/Claude Code via claude_desktop_config.json — talk to it naturally: \"Create a task: set up CI/CD, high priority\" or \"Give me my daily standup\"",
    ],
  },
  {
    href: "https://github.com/akshita270/financial-agent",
    title: "Financial AI Agent",
    description:
      "An autonomous multi-agent system for financial data analysis — one agent pulls live stock prices, fundamentals, and analyst recommendations while a second searches the web for the latest market news, with a Streamlit UI to query both at once.",
    thumbnail: "📈",
    image: "/images/projects/financial-agent.png",
    contain: true,
    color: "#10b981",
    period: "2025",
    live: "https://financial-agent-9mqzctk8pzyj3vbaxdz26t.streamlit.app",
    stack: ["Python", "Streamlit", "Phidata", "GPT-4o mini", "yfinance"],
    slug: "financial-agent",
    highlights: [
      "Two-agent team: a Finance Agent (yfinance tools for stock price, fundamentals, and analyst recommendations) and a Web Search Agent (DuckDuckGo for the latest financial news), each backed by GPT-4o mini",
      "Agents stay in their lane by design — the web agent is explicitly instructed not to fetch stock prices, leaving that strictly to the finance agent's tool calls",
      "Finance Agent renders results as markdown tables for clean side-by-side comparison",
      "Streamlit interface takes any stock, company, or financial question and runs both agents in parallel, showing market data and news side by side",
    ],
  },
  {
    href: "https://github.com/akshita270/speculative-decoding-inference-engine",
    live: "https://speculative-decoding-inference-engine.streamlit.app",
    title: "Speculative Decoding Inference Engine",
    description:
      "A mini LLM inference system built around speculative decoding — a small draft model proposes tokens ahead, and a large target model verifies them in a single batched pass, producing mathematically identical output to standard sampling but significantly faster.",
    thumbnail: "⚡",
    color: "#6366f1",
    period: "2026",
    stack: ["Python", "FastAPI", "Streamlit", "HuggingFace", "PyTorch"],
    slug: "speculative-decoding-inference-engine",
    highlights: [
      "Speculative decoding engine: draft model proposes k tokens, target model verifies all in one batched forward pass — accept/reject rule guarantees output is mathematically identical to sampling from the target alone",
      "Request queue + batcher groups concurrent requests arriving within ~50ms into a single batch instead of dropping them",
      "Semantic cache layer: cosine similarity ≥ 0.92 serves cached responses instantly, bypassing the inference engine entirely",
      "Load-based router: routes to a faster draft model under high load, a better draft model under low load — balancing latency vs. acceptance rate dynamically",
    ],
  },
];
