export const products = [
  {
    href: "https://github.com/akshita270/sehatrx",
    live: "https://sehatrx.vercel.app",
    title: "SehatRx — AI-Powered Consultation to Prescription Platform",
    description:
      "A full-stack healthcare platform that listens to doctor-patient consultations, instantly transcribes them using AI, drafts structured prescriptions, and delivers them to the patient's portal the moment the doctor approves — eliminating paperwork entirely.",
    thumbnail: "🏥",
    image: "/images/projects/sehatrx.png",
    contain: true,
    color: "#0d9488",
    period: "2026",
    stack: ["React", "FastAPI", "Python", "OpenAI Whisper", "JWT", "Vercel"],
    slug: "sehatrx",
    featured: true,
    blog: "https://medium.com/@jakshita770/i-built-sehatrx-an-ai-prescription-app-for-indian-clinics-the-ai-was-the-easy-part-c097417b0d35",
    deck: "/SehatRx-Deck.pdf",
    highlights: [
      "End-to-end workflow: doctor records consultation audio → AI transcribes in real time → LLM drafts a structured prescription → doctor reviews and approves → prescription instantly appears in patient portal",
      "Role-based access for three user types: Doctor (record, review, approve), Patient (view prescriptions), and Family (view family member prescriptions)",
      "AI transcription powered by OpenAI Whisper with LLM-based prescription structuring — extracts diagnosis, medications, dosage, and instructions from free-form speech",
      "JWT-authenticated REST API backend with FastAPI; React frontend deployed on Vercel with real-time prescription delivery",
    ],
    differentiators: [
      {
        icon: "🗣️",
        title: "The doctor just talks — the paperwork writes itself.",
        body: "Instead of typing out a prescription after every patient, the doctor has a normal conversation and the app turns that into a clean, structured prescription automatically. For a doctor seeing 40+ patients a day, that's real time back.",
      },
      {
        icon: "🇮🇳",
        title: "Built for how Indian clinics actually talk.",
        body: "It listens to real consultations — Hindi, English, or the Hindi-English mix most doctors here actually speak in — and catches every word, not just the parts said in English. The prescription comes back in Hindi too, so a patient who can't read English still gets a prescription they can actually understand, even having it read aloud to them.",
      },
      {
        icon: "📱",
        title: "No more lost or illegible prescriptions.",
        body: "The moment the doctor sends it, it's instantly on the patient's portal — and a family member can be linked to see it too. No handwritten slip to lose, no blurry WhatsApp photo of a prescription nobody can read.",
      },
    ],
    engineeringNotes: [
      {
        title: "Removing claim codes without reopening the account-takeover risk",
        body: "Originally required a claim code to link a self-registered patient account to a doctor-created record, to prevent account takeover by anyone who knew a patient's email. In practice this broke onboarding for elderly patients without email, and a separate gap — no dedup check when doctors added a new patient — caused the same person to end up as two disconnected database rows, so a prescription the doctor sent was invisible from the patient's own login. Removed claim codes entirely and replaced them with phone-or-email matching plus automatic record reuse at intake, fixing the onboarding friction and the duplicate-record bug's root cause in one pass.",
      },
    ],
    caseStudy: {
      problemHeadline: "Doctors in Indian clinics spend more time on paperwork than on patients.",
      problem: "A doctor seeing 40+ patients a day handwrites prescriptions for each one — slow, error-prone, and often illegible. Patients lose slips, can't read them, or can't share them with family. No existing tool was built for how Indian clinics actually work.",
      solutionHeadline: "The doctor talks. The prescription writes itself.",
      solution: "SehatRx listens to the consultation, transcribes it in real time using Whisper, drafts a structured prescription via LLM, and delivers it to the patient's portal the moment the doctor approves — zero paperwork, zero delay.",
      whyAIHeadline: "Without AI, this workflow simply can't exist.",
      whyAI: "Real-time speech transcription, multilingual support (Hindi + English code-switching), and extracting diagnosis/medications/dosage from free-form speech are all AI-native problems. A rule-based system can't handle natural conversation. AI is the product, not a feature.",
      tradeoffs: [
        { title: "Whisper (cloud) vs. on-device STT", body: "Whisper gives significantly better accuracy on Hindi-English code-switching than on-device alternatives. The tradeoff is latency and cost per transcription — acceptable for a clinical setting where accuracy is non-negotiable." },
        { title: "LLM prescription drafting vs. structured form input", body: "Free-form speech → LLM structuring is faster for doctors but introduces hallucination risk on medication names. Mitigated by requiring doctor review before any prescription is finalized." },
        { title: "JWT auth vs. OAuth", body: "JWT keeps the backend stateless and avoids third-party OAuth dependency for a clinic-facing product where patients may not have Google accounts. The tradeoff is manual token refresh management." },
      ],
    },
  },
  {
    href: "https://github.com/akshita270/askql",
    live: "https://lnkd.in/gabgdR3i",
    title: "AskQL — Multi-Tenant Text-to-SQL Analytics Platform",
    description:
      "Ask questions about your data in plain English and get back a live SQL query, results table, and auto-generated chart — no SQL knowledge required. A full-stack, multi-tenant platform where each user gets an isolated workspace for their own CSV datasets alongside a shared demo database.",
    thumbnail: "🗄️",
    image: "/images/projects/askql.png",
    contain: true,
    color: "#6366f1",
    period: "2026",
    stack: ["FastAPI", "React", "PostgreSQL", "SQLite", "Google Cloud Run", "GCS", "Vercel", "OpenAI"],
    slug: "askql",
    featured: true,
    deck: "/AskQL-Deck.pdf",
    highlights: [
      "Multi-tenant architecture: each user gets an isolated workspace for uploading CSV datasets alongside a shared demo database",
      "Backend streams generated SQL token-by-token in real time with an AST-based guardrail layer that blocks unauthorized tables, non-SELECT statements, and prompt-injection attempts before any query touches the database",
      "Auto-generated charts rendered from query results — no configuration needed",
      "Internal observability dashboard tracking live usage, cost, and SQL accuracy against a golden evaluation set",
      "Deployed end-to-end: Vercel (frontend), Google Cloud Run (backend), Supabase Postgres, and GCS for durable per-user file persistence",
    ],
    caseStudy: {
      problemHeadline: "Most people can't query their own data — SQL is a barrier.",
      problem: "Business teams sit on valuable data but depend on engineers to write SQL every time they have a question. It slows decisions, creates bottlenecks, and means most data never gets explored at all.",
      solutionHeadline: "Ask a question in English. Get a live SQL query, results, and a chart.",
      solution: "AskQL translates natural language into SQL in real time, streams the query token-by-token, runs it against the user's own isolated dataset, and auto-generates a chart — no SQL knowledge required, no configuration needed.",
      whyAIHeadline: "Natural language → SQL translation is an LLM-native problem.",
      whyAI: "Mapping intent from free-form English to syntactically correct, context-aware SQL across arbitrary schemas is exactly what LLMs excel at. A rule-based approach would require hand-coding every query pattern — AI makes it generalize across any dataset a user uploads.",
      tradeoffs: [
        { title: "LLM-generated SQL vs. pre-built query builder", body: "A visual query builder would be safer but far less flexible — users couldn't express complex joins or aggregations without SQL knowledge anyway. LLM generation handles the full range of questions at the cost of needing a guardrail layer." },
        { title: "AST-based guardrails vs. prompt-only safety", body: "Relying solely on prompt instructions to block unsafe SQL is too fragile for a multi-tenant product. An AST parser that blocks non-SELECT statements and cross-tenant table access before the query touches the database is the only safe approach." },
        { title: "Per-user SQLite vs. shared Postgres", body: "Isolating each user's uploaded CSVs into their own SQLite instance prevents any cross-tenant data leakage without row-level security complexity. The tradeoff is that joins across a user's personal data and the shared demo DB require a query routing layer." },
      ],
    },
  },
  {
    href: "https://github.com/akshita270/startup-copilot",
    title: "Startup Copilot",
    description:
      "An AI co-pilot that generates a complete startup blueprint in minutes using a 7-agent pipeline — idea generation, market research, competitor analysis, revenue modeling, MVP planning, and an investor-ready pitch deck, fully automated.",
    thumbnail: "🚀",
    image: "/images/projects/startup-copilot.png",
    color: "#8b5cf6",
    period: "2026",
    stack: ["Python", "FastAPI", "React", "Vite", "Groq (Llama 3.3-70B)", "Supabase"],
    slug: "startup-copilot",
    featured: true,
    live: "https://startup-copilot-ohe44n0s9-akshita270s-projects.vercel.app",
    blog: "https://tinyurl.com/379j7j5v",
    highlights: [
      "7 sequential agents: Idea Generation → Market Research → Competitor Analysis → Revenue Model → MVP Planner → Synthesis → Pitch Generator",
      "Idea Generation produces 4 startup concepts with name, tagline, problem, target user, and UVP; Market Research adds TAM/SAM/SOM and customer personas",
      "Competitor Analysis surfaces 4-5 real competitors with gap analysis and positioning strategy",
      "MVP Planner outputs core features, tech stack, and a 12-week build timeline; Synthesis produces an executive summary and startup score",
      "Final agent generates an 11-slide pitch deck outline with speaker notes, auto-converted to a downloadable .pptx via python-pptx",
      "Live SSE streaming of pipeline progress to a React frontend, backed by Supabase for run history",
    ],
    caseStudy: {
      problemHeadline: "Founders waste weeks on work that shouldn't take weeks.",
      problem: "Market sizing, competitor research, revenue modeling, pitch decks — each is slow and repetitive, not hard. Most founders either skip them and walk into investor meetings underprepared, or pay consultants for boilerplate output.",
      solutionHeadline: "One idea → 7 agents → full startup blueprint in minutes.",
      solution: "Each agent owns one piece of the blueprint and passes its output to the next. The user types an idea; minutes later they have market research, competitor gaps, a revenue model, MVP roadmap, executive summary, and a downloadable pitch deck.",
      whyAIHeadline: "This product category only exists because of AI.",
      whyAI: "Every output follows patterns an LLM trained on thousands of business documents can reproduce in seconds. Without AI, this requires either a team of analysts or a founder spending nights on tasks that aren't their core skill. AI doesn't just speed it up — it makes the whole thing possible for a solo builder.",
      tradeoffs: [
        { title: "Sequential vs. parallel agents", body: "Agents run in sequence so each one's output feeds the next — the revenue model knows what market research found. Parallel would be faster but loses that cross-agent context." },
        { title: "Groq (Llama 3.3-70B) vs. GPT-4", body: "Groq is significantly faster for structured business writing, but has tighter rate limits across 7 back-to-back LLM calls." },
        { title: "Fixed pipeline vs. dynamic routing", body: "Always runs all 7 agents in order. Simpler to debug and keeps output format predictable — which matters when the PPTX generator needs to parse structured sections." },
      ],
    },
  },
  {
    href: "https://github.com/akshita270/GeneSight",
    title: "GeneSight – Genomic Intelligence Pipeline",
    description:
      "An agentic AI system that automatically generates scientific hypotheses from genomics literature and biological databases using an 8-agent pipeline — from literature retrieval to knowledge graph construction and evidence-validated hypothesis generation.",
    thumbnail: "🧬",
    image: "/images/projects/genesight.png",
    color: "#06b6d4",
    period: "2026",
    stack: ["Python", "FastAPI", "GPT-4o", "Neo4j", "spaCy", "Streamlit"],
    slug: "genesight",
    featured: true,
    highlights: [
      "8-agent pipeline: Task Planner → Literature Retrieval (PubMed/NCBI Entrez) → Info Extraction (spaCy biomedical NER) → Genomics DB lookup (NCBI Gene + UniProt) → Knowledge Graph (Neo4j) → Hypothesis Generation (GPT-4o) → Evidence Validation → Report Generation",
      "Pulls real biomedical literature from PubMed and cross-references NCBI Gene and UniProt for gene/protein metadata",
      "Builds a persistent knowledge graph in Neo4j linking genes, diseases, and supporting evidence",
      "Ranks generated hypotheses by confidence score with supporting evidence attached — e.g. querying \"new gene relationships related to Alzheimer's disease\" returns ranked, evidence-backed hypotheses",
      "FastAPI backend with async job polling (`/query`, `/status/{job_id}`, `/result/{job_id}`) and a Streamlit front-end",
    ],
    caseStudy: {
      problemHeadline: "Scientific hypothesis generation takes researchers months — most leads never get explored.",
      problem: "Biomedical researchers manually scan thousands of papers, cross-reference gene databases, and piece together evidence before forming a single hypothesis. Most promising gene-disease connections are never explored simply because the process doesn't scale.",
      solutionHeadline: "Type a query. Get ranked, evidence-backed hypotheses in minutes.",
      solution: "An 8-agent pipeline retrieves real literature from PubMed, extracts biomedical entities with spaCy NER, cross-references NCBI Gene and UniProt, builds a knowledge graph in Neo4j, generates hypotheses with GPT-4o, and validates them against evidence — all automatically.",
      whyAIHeadline: "No rule-based system can read papers, extract meaning, and reason across a knowledge graph.",
      whyAI: "Biomedical NER, literature comprehension, and hypothesis generation from sparse evidence are all tasks that require deep language understanding. GPT-4o reasons across the knowledge graph to surface connections a keyword search would never find. AI doesn't assist the pipeline — it is the pipeline.",
      tradeoffs: [
        { title: "GPT-4o vs. biomedical fine-tuned models", body: "GPT-4o's general reasoning outperforms smaller domain-specific models on cross-domain hypothesis generation. The tradeoff is cost and latency per query — acceptable for a research tool where quality matters more than speed." },
        { title: "Neo4j knowledge graph vs. vector similarity search", body: "A graph database captures explicit gene-disease-evidence relationships and supports multi-hop queries. Vector search would be faster for retrieval but loses the structured relationship semantics that make hypothesis validation meaningful." },
        { title: "8-agent sequential pipeline vs. single LLM call", body: "Each agent specializes in one task — retrieval, extraction, graph construction, generation, validation — producing far more accurate output than asking one prompt to do everything. The cost is pipeline latency and complexity." },
      ],
    },
  },
  {
    href: "https://github.com/akshita270/RAG-comparison-experiment",
    title: "RAG Comparison Experiment",
    description:
      "A structured research experiment comparing four RAG architectures — Vanilla, HyDE, GraphRAG, and Agentic RAG — on their ability to reduce hallucinations when answering questions about AI/ML research papers from ArXiv.",
    thumbnail: "📚",
    image: "/images/projects/rag-comparison-experiment.jpg",
    color: "#10b981",
    period: "2026",
    stack: ["Python", "ChromaDB", "RAGAS", "Claude/GPT", "LLM-as-Judge"],
    slug: "rag-comparison-experiment",
    research: true,
    live: "https://huggingface.co/spaces/akshita27/RAG-comparison-dashboard",
    blog: "https://tinyurl.com/3jyjvhaz",
    highlights: [
      "4 architectures benchmarked head-to-head: Vanilla RAG (baseline), HyDE RAG (hypothetical-document embeddings), GraphRAG (knowledge graph + vector hybrid), and Agentic RAG (ReAct tool-use agent)",
      "Each architecture answers the same 25 questions over the same 25 ArXiv papers — 100 LLM answer calls total, plus ~200 scoring calls",
      "Evaluated on faithfulness, relevance, context precision, and latency using RAGAS metrics and a blind LLM-as-judge (1–5 scoring)",
      "Produces a results CSV and 4 comparison charts to identify which retrieval strategy actually reduces hallucination in production RAG systems",
    ],
  },
  {
    href: "https://github.com/akshita270/-ReflexRAG",
    title: "ReflexRAG",
    description:
      "A production-grade RAG system for clinical research PDFs, combining hybrid retrieval, cross-encoder reranking, and a dual self-reflection grading loop that validates both retrieval quality and answer faithfulness before returning a response.",
    thumbnail: "🔁",
    image: "/images/projects/reflexrag.png",
    color: "#ec4899",
    period: "2026",
    stack: ["Python", "FastAPI", "FAISS", "BM25", "Next.js", "GPT-4o mini"],
    slug: "reflexrag",
    live: "https://reflexrag.netlify.app",
    highlights: [
      "9-stage pipeline: PDF load/clean → sentence chunking → FAISS + BM25 hybrid indexing → Reciprocal Rank Fusion → MMR diversity filtering → cross-encoder reranking → retrieval grading → GPT-4o mini generation → answer grading",
      "Two self-reflection checkpoints: a retrieval grader and an answer grader, each retrying with query expansion if validation fails",
      "Rule-based table parser accurately extracts structured data from clinical tables (e.g. cardiac murmur characteristics) instead of mangling them in plain-text chunks",
      "Session-scoped, in-memory FAISS index per PDF upload — no shared state between users",
      "Deployed live on AWS EC2 with a Next.js + Tailwind frontend on Netlify",
    ],
  },
  {
    href: "https://github.com/akshita270/memoryos-benchmark",
    live: "https://huggingface.co/spaces/akshita27/memoryos-benchmark",
    title: "MemoryOS Benchmark",
    description:
      "A controlled benchmark proving that an AI agent with a 3-layer memory system consistently outperforms a stateless baseline across 50 scripted tasks spanning 10 sessions — quantifying exactly how much persistent memory improves an agent.",
    thumbnail: "🧠",
    image: "/images/projects/memoryos-benchmark.png",
    color: "#f59e0b",
    period: "2026",
    stack: ["Python", "OpenAI API", "ChromaDB", "Agentic AI"],
    slug: "memoryos-benchmark",
    research: true,
    highlights: [
      "3-layer memory architecture: working memory (in-session, cleared each session), episodic memory (ChromaDB, semantic search over past messages), and semantic memory (LLM-compressed long-term user profile)",
      "A deterministic MemoryRouter combines all three layers before every LLM call — no LLM calls inside the router itself",
      "Benchmarked against a stateless baseline agent across 50 tasks following a fictional user whose facts are introduced early and must be recalled and synthesized later",
      "Memory-equipped agent's score diverges clearly from the stateless baseline by session 4, reaching near-perfect scores on complex synthesis tasks by sessions 7–10",
    ],
  },
  {
    href: "https://github.com/akshita270/devassist-workspace",
    title: "DevAssist — Personal Dev Workspace MCP Server",
    description:
      "A Model Context Protocol (MCP) server that connects Claude to a local dev workspace — managing tasks, searching notes, syncing GitHub issues, and visualizing everything in a web dashboard. Implements all 3 MCP primitives: Tools, Resources, and Prompts.",
    thumbnail: "🛠️",
    image: "/images/projects/devassist-workspace.svg",
    color: "#8b5cf6",
    period: "2026",
    stack: ["Python", "FastMCP", "FastAPI", "SQLite", "GitHub REST API"],
    slug: "devassist-workspace",
    highlights: [
      "13 MCP tools spanning task management (create/complete/delete/list tasks, notes search) and GitHub integration (list/create/close issues, link tasks to issues, sync issues as local tasks)",
      "Implements all 3 MCP primitives: Tools (callable functions), Resources (read-only data like devassist://tasks and devassist://notes/{filename}), and Prompts (reusable templates like daily_standup and project_brief)",
      "SQLite-backed task and note storage, with markdown notes exposed directly as MCP Resources",
      "FastAPI + vanilla JS web dashboard for live task management, GitHub issue sync, and notes overview alongside the MCP server",
      "Drops straight into Claude Desktop/Claude Code via claude_desktop_config.json — talk to it naturally: \"Create a task: set up CI/CD, high priority\" or \"Give me my daily standup\"",
    ],
  },
  {
    href: "https://github.com/akshita270/financial-agent",
    title: "Financial AI Agent",
    description:
      "An autonomous multi-agent system for financial data analysis — one agent pulls live stock prices, fundamentals, and analyst recommendations while a second searches the web for the latest market news, with a Streamlit UI to query both at once.",
    thumbnail: "📈",
    image: "/images/projects/financial-agent.svg",
    contain: false,
    color: "#10b981",
    period: "2025",
    live: "https://financial-agent-9mqzctk8pzyj3vbaxdz26t.streamlit.app",
    stack: ["Python", "Streamlit", "Phidata", "GPT-4o mini", "yfinance"],
    slug: "financial-agent",
    highlights: [
      "Two-agent team: a Finance Agent (yfinance tools for stock price, fundamentals, and analyst recommendations) and a Web Search Agent (DuckDuckGo for the latest financial news), each backed by GPT-4o mini",
      "Agents stay in their lane by design — the web agent is explicitly instructed not to fetch stock prices, leaving that strictly to the finance agent's tool calls",
      "Finance Agent renders results as markdown tables for clean side-by-side comparison",
      "Streamlit interface takes any stock, company, or financial question and runs both agents in parallel, showing market data and news side by side",
    ],
  },
  {
    href: "https://github.com/akshita270/speculative-decoding-inference-engine",
    live: "https://speculative-decoding-inference-engine.streamlit.app",
    title: "Speculative Decoding Inference Engine",
    description:
      "A mini LLM inference system built around speculative decoding — a small draft model proposes tokens ahead, and a large target model verifies them in a single batched pass, producing mathematically identical output to standard sampling but significantly faster.",
    thumbnail: "⚡",
    image: "/images/projects/speculative-decoding.svg",
    contain: false,
    color: "#6366f1",
    period: "2026",
    stack: ["Python", "FastAPI", "Streamlit", "HuggingFace", "PyTorch"],
    slug: "speculative-decoding-inference-engine",
    highlights: [
      "Speculative decoding engine: draft model proposes k tokens, target model verifies all in one batched forward pass — accept/reject rule guarantees output is mathematically identical to sampling from the target alone",
      "Request queue + batcher groups concurrent requests arriving within ~50ms into a single batch instead of dropping them",
      "Semantic cache layer: cosine similarity ≥ 0.92 serves cached responses instantly, bypassing the inference engine entirely",
      "Load-based router: routes to a faster draft model under high load, a better draft model under low load — balancing latency vs. acceptance rate dynamically",
    ],
  },
];
