export const timeline = [
  {
    company: "KareXpert",
    title: "AI Engineer",
    date: "Sep 2025 – Present",
    description: "Delhi, India · Full-time",
    logo: "🏥",
    skills: ["FastAPI", "Python", "RAG", "Gemini API", "OpenAI", "Qdrant"],
    responsibilities: [
      "Developed backend services and REST APIs using Python and FastAPI for KareXpert's AI-Powered Business Intelligence platform, enabling self-service dashboard creation and embedded analytics while replacing Microsoft Power BI and eliminating recurring licensing costs of approximately ₹70K–80K per month.",
      "Designed and implemented an AI-powered Chart Builder in BI Tool using the Gemini API, engineering prompt workflows, LLM response validation, and backend orchestration to generate interactive visualizations from natural-language prompts, reducing dashboard creation time by 75%.",
      "Built a Retrieval-Augmented Generation (RAG) chatbot using Python, FastAPI, Qdrant, and OpenAI APIs, implementing semantic retrieval, prompt engineering, and response orchestration to enable conversational access to project tasks, documentation, and workflow insights.",
    ],
  },
  {
    company: "Boston University — Faculty of Computing & Data Sciences",
    title: "Graduate Research Assistant",
    date: "Aug 2024 – Dec 2024",
    description: "Boston, MA, USA · Part-time",
    logo: "🎓",
    skills: ["LLMs", "RAG", "Deep Learning", "Research"],
    responsibilities: [
      "Collaborated with CS department researchers on AI and retrieval-based system concepts.",
      "Gained early exposure to the foundations of LLMs and RAG pipelines that shaped current professional focus and projects.",
      "Contributed to AI research at a top-20 U.S. research university, developing and evaluating deep learning architectures.",
      "Developed understanding of agentic systems that became the backbone of subsequent project work including GeneSight and StartupAI.",
    ],
  },
  {
    company: "1Gen",
    title: "Data Science Intern",
    date: "Sep 2022 – Jan 2023",
    description: "Delhi, India · Internship",
    logo: "💡",
    skills: ["Python", "SQL", "Machine Learning", "Tableau", "EHR"],
    responsibilities: [
      "Leveraged Python, SQL, and machine learning algorithms (regression, clustering) to analyze 15,000+ Electronic Health Records (EHRs).",
      "Uncovered significant trends that boosted precision medicine adoption by 20% and reduced patient stress by 15%.",
      "Enhanced operational efficiency by 30% by automating EHR data processing with Python.",
      "Advanced mindfulness-based healthcare insights through Tableau dashboards for clinical teams.",
    ],
  },
  {
    company: "Boston University",
    title: "Master of Science — Applied Data Analytics",
    date: "Sep 2023 – Jan 2025",
    description: "Boston, Massachusetts, USA",
    logo: "🏛️",
    skills: ["ML", "Data Analytics", "Neural Networks", "AI"],
    responsibilities: [
      "Course Work: Deep Learning, Data Structures & Algorithms, Machine Learning & AI, Database Management System.",
      "Graduate Research Assistant at Faculty of Computing & Data Sciences (CS dept.)",
      "Specialized in AI/ML, healthcare analytics, and big data systems.",
    ],
  },
  {
    company: "Guru Gobind Singh Indraprastha University",
    title: "Bachelor of Technology — Computer Science & Engineering",
    date: "Sep 2019 – Jul 2023",
    description: "Delhi, India",
    logo: "🎓",
    skills: ["DSA", "DBMS", "OOP", "Computer Networks"],
    responsibilities: [
      "Coursework: Data Structures & Algorithms, DBMS, OOP, Operating Systems, Computer Networks, Software Engineering.",
      "Secured 2nd Prize in \"Sell Your Way\" product marketing competition (MBA Dept.)",
      "Developed early passion for data analysis and AI applications.",
    ],
  },
];
